using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Turmerik.Cloneable;
using Turmerik.Collections;
using Turmerik.CodeAnalysis.Core.Components;

namespace Turmerik.MsVSTextTemplating.Components
{
    public static partial class ParsedClnblTypeMemberDeclaration
    {
        public interface IClnbl : ParsedTypeMemberDeclaration.IClnbl
        {
            bool HasImplementation { get; }
            bool HasAutoGeneratedImplementation { get; }
            bool IsClnblMemberDef { get; }
            bool IsClnblMemberImpl { get; }
        }

        public class Immtbl : ParsedTypeMemberDeclaration.Immtbl, IClnbl
        {
            public Immtbl(IClnbl src) : base(src)
            {
                HasImplementation = src.HasImplementation;
                HasAutoGeneratedImplementation = src.HasAutoGeneratedImplementation;
                IsClnblMemberDef = src.IsClnblMemberDef;
                IsClnblMemberImpl = src.IsClnblMemberImpl;
            }

            public bool HasImplementation { get; }
            public bool HasAutoGeneratedImplementation { get; }
            public bool IsClnblMemberDef { get; }
            public bool IsClnblMemberImpl { get; }
        }

        public class Mtbl : ParsedTypeMemberDeclaration.Mtbl, IClnbl
        {
            public Mtbl()
            {
            }

            public Mtbl(IClnbl src) : base(src)
            {
                HasImplementation = src.HasImplementation;
                HasAutoGeneratedImplementation = src.HasAutoGeneratedImplementation;
                IsClnblMemberDef = src.IsClnblMemberDef;
                IsClnblMemberImpl = src.IsClnblMemberImpl;
            }

            public bool HasImplementation { get; }
            public bool HasAutoGeneratedImplementation { get; set; }
            public bool IsClnblMemberDef { get; set; }
            public bool IsClnblMemberImpl { get; set; }
        }

        public static Immtbl ToImmtbl(
            this IClnbl src) => new Immtbl(src);

        public static Immtbl AsImmtbl(
            this IClnbl src) => src as Immtbl ?? src?.ToImmtbl();

        public static Mtbl ToMtbl(
            this IClnbl src) => new Mtbl(src);

        public static Mtbl AsMtbl(
            this IClnbl src) => src as Mtbl ?? src?.ToMtbl();

        public static ReadOnlyCollection<Immtbl> ToImmtblCllctn(
            this IEnumerable<IClnbl> src)
        {
            return src?.Select(
                item => item?.AsImmtbl()).RdnlC();
        }

        public static ReadOnlyCollection<Immtbl> AsImmtblCllctn(
            this IEnumerable<IClnbl> src) =>
            src as ReadOnlyCollection<Immtbl> ?? src?.ToImmtblCllctn();

        public static List<Mtbl> ToMtblList(
            this IEnumerable<IClnbl> src) => src?.Select(
                item => item?.AsMtbl()).ToList();

        public static List<Mtbl> AsMtblList(
            this IEnumerable<IClnbl> src) => src as List<Mtbl> ?? src?.ToMtblList();

        public static ReadOnlyDictionary<TKey, Immtbl> AsImmtblDictnr<TKey>(
            IDictionaryCore<TKey, IClnbl> src) => src as ReadOnlyDictionary<TKey, Immtbl> ?? (src as Dictionary<TKey, Mtbl>)?.ToDictionary(
                kvp => kvp.Key, kvp => kvp.Value?.AsImmtbl()).RdnlD();

        public static Dictionary<TKey, Mtbl> AsMtblDictnr<TKey>(
            IDictionaryCore<TKey, IClnbl> src) => src as Dictionary<TKey, Mtbl> ?? (src as ReadOnlyDictionary<TKey, Immtbl>)?.ToDictionary(
                kvp => kvp.Key, kvp => kvp.Value?.AsMtbl());
    }
}
